### ISSUE TITLE
Suporte à requisição de cadastros

### ISSUE THREAD

**Issue by tiagodalloca** [MrDallOca/PDpedia#10]
## TODO
- [x] Criar tabela Requisicao (ID, Nome, Senha, Data(da requisicao))
- [x] Implementar na API
- [x] Atualizar documentação
- [ ] Fazer testes e procurar bugs
### Guardar IP
- [x] Criar campo na tabela `Requisicao`
- [x] Alterar [config.json](https://github.com/MrDallOca/PDpedia/tree/api-requisicao/api/config.json)
