### ISSUE TITLE
Autenticação para uso da API

### ISSUE THREAD

**Issue by tiagodalloca** [MrDallOca/PDpedia#7]
A API [atualmente](https://github.com/MrDallOca/PDpedia/releases/tag/v0.0.1) está simplesmente funcionando como um intermediador entre o banco e o cliente HTTP. Todas as tabelas e todos os métodos (PUT, GET, POST, DELETE) estão disponíveis à _qualquer_ cliente. Isso evidentemente é ruim.

O próximo passo é restringir métodos e tabelas "críticos", isso é, aqueles que não podem ser alterados por qualquer um ou que contém informações que não podem ser expostas. Ao meu ver são:
- **Senha do Usuário**. Não pode ser visualizada
- **Usuario, Edicao_[Acontecimento, Artigos, Biografia]**. Tabelas que não podem ser alteradas sem restrição.
### TODO:
- [x] **Método de login** para API. Algo que permita fazer o login mas sem fazer a verificação de senhas no cliente.
- [x] **Limitar acesso à senha do Usuario**
- [x] **Limitar acesso à métodos que alterem tabelas críticas**

Ver [dev-token](https://github.com/MrDallOca/PDpedia/commits/dev-token)
